# BoardConfig for OPPO K10 5G (PGJM10) - MT6895
# Infinity X Android 16

TARGET_BOARD_PLATFORM := mt6895
TARGET_BOARD_PLATFORM_VARIANT := cortex-a78

# Architecture
TARGET_CPU_ABI := arm64-v8a
TARGET_CPU_ABI2 := armeabi-v7a
TARGET_ARCH := arm64
TARGET_ARCH_VARIANT := armv8-2a
TARGET_CPU_VARIANT := cortex-a78
TARGET_CPU_VARIANT_Release := cortex-a78

# 64-bit only
TARGET_2ND_CPU_ABI := 
TARGET_2ND_ARCH := 

# Device paths
DEVICE_PATH := device/oppo/pgjm10
BOARD_VENDOR := oppo
TARGET_DEVICE := pgjm10

# Bootloader
TARGET_BOOTLOADER_BOARD_NAME := mt6895
TARGET_NO_BOOTLOADER := true

# Kernel
BOARD_KERNEL_BASE := 0x00000000
BOARD_KERNEL_PAGESIZE := 4096
BOARD_KERNEL_CMDLINE := androidboot.hardware=mt6895 androidboot.mediawan.platform=mt6895
BOARD_MKBOOTIMG_ARGS := --kernel_offset 0x00008000 --ramdisk_offset 0x04000000 --tags_offset 0x03e00000
TARGET_KERNEL_CONFIG := pgjm10_defconfig
TARGET_KERNEL_SOURCE := kernel/oppo/mt6895

# DTBO
BOARD_INCLUDE_DTBO_IN_BOOTIMG := true
BOARD_BOOTIMG_DTBO_SIZE := 0x1000000
BOARD_BOOTIMG_DTBO_OFFSET := 0x01700000

# Partitions
BOARD_BOOTIMAGE_PARTITION_SIZE := 67108864
BOARD_RECOVERYIMAGE_PARTITION_SIZE := 67108864
BOARD_SYSTEMIMAGE_PARTITION_SIZE := 3221225472
BOARD_VENDORIMAGE_PARTITION_SIZE := 2147483648
BOARD_VENDOR_BOOTIMAGE_PARTITION_SIZE := 67108864

# Super partition
BOARD_SUPER_PARTITION_SIZE := 12884901888
BOARD_SUPER_PARTITION_METADATA_SIZE := 16928

# File system
TARGET_USERIMAGES_USE_EXT4 := true
TARGET_USERIMAGES_USE_F2FS := true

# AVB
BOARD_AVB_ENABLE := true
BOARD_AVB_VBMETA_SYSTEM := system
BOARD_AVB_VBMETA_SYSTEM_KEY_PATH := external/avb/test/data/testkey_rsa2048.pem
BOARD_AVB_VBMETA_SYSTEM_ALGORITHM := SHA256_RSA2048
BOARD_AVB_VBMETA_VENDOR := vendor
BOARD_AVB_VBMETA_VENDOR_KEY_PATH := external/avb/test/data/testkey_rsa2048.pem
BOARD_AVB_VBMETA_VENDOR_ALGORITHM := SHA256_RSA2048

# SELinux
BOARD_SEPOLICY_DIRS += device/oppo/pgjm10/sepolicy

# HIDL
DEVICE_MANIFEST_FILE := $(LOCAL_PATH)/manifest.xml

# Properties
TARGET_SYSTEM_PROP := $(LOCAL_PATH)/system.prop
TARGET_VENDOR_PROP := $(LOCAL_PATH)/vendor.prop
TARGET_PRODUCT_PROP := $(LOCAL_PATH)/product.prop

# Treble
PRODUCT_FULL_TREBLE_OVERRIDE := true

# Copy files
BOARD_VENDOR_SEPOLICY_DIRS += $(LOCAL_PATH)/sepolicy/vendor
BOARD_PROPERTY_OVERRIDES += $(LOCAL_PATH)/property_defaults.prop

# Media
MEDIA_BCB_ENABLED := true

# Recovery
TARGET_RECOVERY_FSTAB := $(LOCAL_PATH)/rootdir/fstab.mt6895
TARGET_RECOVERY_DEVICE_MODULES += android.hardware.health@2.1

# Graphics
TARGET_USES_GRALLOC1 := true
TARGET_USES_HWC2 := true

# Power
TARGET_POWERHAL_MODE_EXT := $(LOCAL_PATH)/power

# Bluetooth
BOARD_BLUETOOTH_BDROID_BUILDCFG_INCLUDE_DIR := $(LOCAL_PATH)/bluetooth

# WiFi
WPA_SUPPLICANT_VERSION := VER_0_8_X
BOARD_WPA_SUPPLICANT_DRIVER := NL80211
BOARD_HOSTAPD_DRIVER := NL80211
